apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-2
spec:
  replicas: 1
  selector:
    app: theia-2
  template:
    metadata:
      name: theia-2
      labels:
        app: theia-2
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
        - name: pvc-pv
          persistentVolumeClaim:
            claimName: pvc-03
      containers:
        - name: theia
          image: nilltobesoft/blue
          volumeMounts:
            - name: pvc-pv
              mountPath: /home/project2
          ports:
            - containerPort: 3000
