apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  selector:
    app: theia-blue
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
  externalTrafficPolicy: Local
