apiVersion: v1
kind: Service
metadata:
  name: nodeport2
spec:
  selector:
    app: theia2
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
  externalTrafficPolicy: Local
