apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-02
  labels:
    pv: pv-02
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  local:
    path: /project
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - { key: kubernetes.io/hostname, operator: In, values: [k8s-node2] }
